# Generated by Django 3.2.12 on 2022-03-22 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentname',
            old_name='lastnmae',
            new_name='lastname',
        ),
    ]
