# Generated by Django 3.2.12 on 2022-03-22 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_rename_lastnmae_agentname_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcedpuresults',
            name='entered_by_user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
