# Generated by Django 3.2.12 on 2022-03-22 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0003_announcedpuresults_entered_by_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcedpuresults',
            name='date_entered',
            field=models.DateTimeField(),
        ),
    ]
