# Generated by Django 3.2.12 on 2022-03-22 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0005_alter_lga_date_entered'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollingunit',
            name='polling_unit_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
