# Generated by Django 3.2.12 on 2022-03-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0009_alter_ward_date_entered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcedpuresults',
            name='date_entered',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
